import { Edge } from "@xyflow/react";

export const initialEdges: Edge[] = [
  {
    id: "group-1->node2",
    source: "group-1",
    target: "node-2",
    type: "custom",
    label: "Group-Node2",
    animated: true,
    style: { stroke: "blue", strokeWidth: 2 },
    labelStyle: { fill: "#000", fontSize: 14, fontWeight: "bold" },
  },
  {
    id: "group-1->node3",
    source: "group-1",
    target: "node-3",
    type: "custom",
    label: "Group-Node3",
    animated: true,
    style: { stroke: "green", strokeWidth: 2 },
    labelStyle: { fill: "#000", fontSize: 14, fontWeight: "bold" },
  },
  {
    id: "node2->node4",
    source: "node-2",
    target: "node-4",
    type: "custom",
    animated: true,
    label: "Animated Edge",
    style: { stroke: "yellow", strokeWidth: 2 },
    labelStyle: { fill: "#00ff00", fontSize: 14 },
  },
  {
    id: "node3->node5",
    source: "node-3",
    target: "node-5",
    type: "custom",
    animated: false,
    label: "Another Edge",
    style: { stroke: "purple", strokeWidth: 2 },
    labelStyle: { fill: "#ff00ff", fontSize: 12 },
  },
  {
    id: "node4->node9",
    source: "node-4",
    target: "node-9",
    type: "custom",
    animated: false,
    label: "Another Edge",
    style: { stroke: "orange", strokeWidth: 2 },
    labelStyle: { fill: "#000", fontSize: 12 },
  },
  {
    id: "node5->node9",
    source: "node-5",
    target: "node-9",
    type: "custom",
    animated: true,
    style: { stroke: "red", strokeWidth: 2 },
    labelStyle: { fill: "#fff", fontSize: 12 },
  },
  {
    id: "group-1->node7",
    source: "group-1",
    target: "node-7",
    type: "custom",
    animated: false,
  },
];
